export const metadata = {
  title: 'My new Next.js Page',
  description: 'Generated by DosCoutos',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
